### ISSUE TITLE
Tematika in podatki

### ISSUE THREAD

**Issue by jaanos** [VezensekKaja/APPR-2015-16#1]
Manjka ti opis tematike in seznam povezav do podatkov, tako da te prosim, da ju dodaš v datoteko `README.md`.

**Comment by VezensekKaja** [comment]
Dodala sem tematiko, sedaj me zanima ali seznam povezav pomeni povezave do spletnih virov ali csv/html datotek na gitu?
Zanima me še ali morajo biti podatki prav iz različnih virov ali lahko iz istega vendar v različnih oblikah?

**Comment by jaanos** [comment]
Kot seznam povezav je mišljem seznam povezav do spletnih strani, ki jih boš bodisi uvozila, oziroma si od tam pridobila podatke v CSV ali drugi obliki. Seveda te vseeno naloži v repozitorij.

Ni nujno, da so podatki iz različnih virov - priporočljivo pa je, da uvoziš kake podatke, ki jih nimaš možnosti izvoziti v CSV. Tako priporočam, da poiščeš še kake podatke iz kje drugje kot iz statističnega urada.
