### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#10]
Shiny mi doma deluje tudi v poročilu.
Me pa samo zanima še, kaj narediti, da bo y os pri prikazu polovica trenutne vrednosti, saj sedaj le sešteje vrednosti januarja in julija, kar da še enkrat višjo plačo, kot bi jo moralo prikazati. ukaz '/2' seveda ne deluje..

**Comment by jaanos** [comment]
Ena možnost bi bila, da prikažeš npr. samo januarske plače - v tem primeru dodaj k `filter` še pogoj `mesec == "Januar"`. Seveda daš lahko uporabniku tudi izbiro, za kateri mesec naj bodo prikazani podatki.

Lahko pa prikažeš oba podatka, vsakega v svojem stolpcu. V tem primeru k `aes_string` dodaj še parameter `fill = "mesec"`, pri `geom_bar` pa namesto parametra `fill` podaj `position = "dodge"` (če bi želela sama nastaviti barve, bi to morala storiti npr. s funkcijo `scale_fill_manual`).

**Comment by VezensekKaja** [comment]
To mi je sedaj uspelo.
Dodala sem še drug shiny in sedaj imam problem, da mi pri nekateri mestih v tabeli prikaže samo eno barvo (torej upošteva samo enega izmed mesecev) čeprav sem pogledala v tabelo in ima podana podatka za oba meseca.

**Comment by jaanos** [comment]
Problem se pojavi tam, kjer v enem mesecu razmerje med bruto plačo in površino preseže 50, v drugem pa ne.

Ena možnost bi bila, da izpišeš vse podatke za občine, ki v vsaj enem mesecu v izbranem letu presežejo izbrano mejo. Takole nekako bi šlo:

``` R
    zdr.leto <- zdr %>% filter(leto == input$izberi)
    ggplot(zdr.leto %>% group_by(kraj) %>%
             summarise(razmerje = max(bruto/povrsina)) %>%
             filter(razmerje > 50) %>% inner_join(zdr.leto, by = "kraj"),
           aes_string(x = "kraj", y = input$izb, fill = "mesec")) +
      geom_bar(stat="identity",position = "dodge",size=10) +
      coord_flip()
```

Tukaj najprej zbereš želene podatke, nato pa za vsak kraj izračunaš največje razmerje in ohraniš tiste kraje, pri katerih maksimalno razmerje preseže 50. Potem te podatke po kraju združiš s prvotnimi, da se pokažejo vsi želeni podatki.

**Comment by VezensekKaja** [comment]
Najlepša hvala.
