### ISSUE TITLE
analiza

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#11]
Sedaj sem se lotila še analize podatkov, ampak mi že pri začetnem grafu, ki ga hočem izrisati javi napako, da ggplot ne zna delati z numeričnimi vrednostmi..

**Comment by jaanos** [comment]
`ggplot` pričakuje celotno razpredelnico in ne samo enega stolpca. Tako bo potrebno podati razpredelnico `zdr`, ki pa ji bo treba še dodati stolpec `datum` - ta naj bo tipa `Date`, da se datumi pravilno prikažejo na grafu:

``` R
ggplot(zdr %>% filter(kraj == "Ljubljana") %>%
         mutate(datum = paste(1, substr(mesec, 1, 3), leto) %>%
                  strptime("%d %b %Y") %>% as.Date()),
       aes(x=datum, y=bruto)) +
  xlim(as.Date("2007-01-01"), as.Date("2026-01-01")) +
  geom_line(size=0.5)+
  geom_point(size=3, fill="black")+
  ggtitle("Napoved rasti bruto plač do leta 2026")+
  geom_smooth(method = "lm",formula = y ~ x+I(x^2)+I(x^3),
              size = 1, fullrange = TRUE)
```

Podatki so tukaj prikazani samo za eno občino, da je graf bolj pregleden. Iz meseca in leta se potem sestavi niz, ki predstavlja prvi dan v mesecu, in ta se pretvori v datum. Seveda morajo tudi meje biti istega tipa.

**Comment by VezensekKaja** [comment]
sedaj mi pravi, da ne prepozna funkcije ggplot, čeprav jo imam naloženo?

**Comment by VezensekKaja** [comment]
sedaj je naredil..

**Comment by VezensekKaja** [comment]
Imam še problem kako izpisati koeficient in prosti člen, da bom lahko predstavila podatke..

**Comment by jaanos** [comment]
Glede na to, da napoveduješ glede na stolpec `datum`, bi ga bilo smiselno dodati kar v `zdr` - mimogrede lahko narediš še stolpec `timestamp`, saj `lm` ne zna direktno delati z datumskimi vrednostmi:

``` R
zdr <- zdr %>% mutate(datum = paste(1, substr(mesec, 1, 3), leto) %>%
                        strptime("%d %b %Y") %>% as.Date()) %>%
  mutate(timestamp = as.numeric(datum))
```

Potem lahko pri risanju grafov uporabiš samo `zdr` in `filter`.

Sedaj lahko zgradiš model na isti način kot pri `geom_smooth`, le da uporabiš ustrezna imena stolpcev:

``` R
lin <- lm(data = zdr, bruto ~ timestamp+I(timestamp^2)+I(log(timestamp)))
```

Koeficiente lahko tako dobiš iz `lin$coefficients`. Pri napovedih bo treba leta najprej pretvoriti v datume, nato pa še nazaj v števila (lahko bi seveda delala napovedi tudi za konkretne datume):

``` R
predict(lin, data.frame(timestamp = paste0(c(2015:2021), "-1-1") %>%
                          as.Date() %>% as.numeric()))
```

**Comment by VezensekKaja** [comment]
Zanima me samo še, če se da pri napovedi, ki jo izpišem preimenovati naslovne vektorje iz 1,2..  v 2016,2017...

**Comment by jaanos** [comment]
Lahko narediš npr.

``` R
setNames(napoved, c(2015:2021))
```

Mimogrede, pri risanju grafov odstrani `mutate`, saj stolpec `datum` zdaj že imaš in ti ga ni treba računati še enkrat.

**Comment by VezensekKaja** [comment]
očitno zbrišem preveč ali premalo, saj mi potem ggplot ne dela več..

**Comment by jaanos** [comment]
`%>% as.Date())` je še odveč - bil je namreč znotraj `mutate`, od katerega je ostal tudi zaklepaj.

**Comment by VezensekKaja** [comment]
sem prej zbrisala tudi to pa mi je vrnilo to napako: ggplot2 doesn't know how to deal with data of class uneval, zato sem potem pustila..

**Comment by jaanos** [comment]
Takole bi moralo delovati:

``` R
g1 <- ggplot(zdr %>% filter(kraj == "Ljubljana"),
       aes(x=datum, y=bruto)) +
  xlim(as.Date("2007-01-01"), as.Date("2021-01-01")) +
  geom_line(size=0.5)+
  geom_point(size=3, fill="black")+
  ggtitle("Napoved rasti bruto plač do leta 2021")+
  geom_smooth(method = "lm",formula = y ~ x+I(x^(2))+I(log(x)), size = 1, fullrange = TRUE)
```

**Comment by VezensekKaja** [comment]
sedaj deluje. Ali moram še kaj spremeniti, da bo projekt končan?

**Comment by jaanos** [comment]
Še eno stvar opažam: na grafih prikazuješ podatke za eno samo občino, pri napovedih pa uporabiš vse podatke, zato se napovedi ne ujemajo z grafi. Dodaj še torej ustrezna filtra pri podatkih za napovedi.

Drugače pa izgleda v redu, tako da lahko dodam povezavo na končno različico, ko meniš, da si končala. Medtem se lahko s profesorjem domeniš za termin zagovora.

**Comment by VezensekKaja** [comment]
Sem dodala, sedaj bi moralo biti pravilno. Hvala za vašo pomoč.
Prosim, da me dodate na končno različico. Bom pisala profesorju.

**Comment by jaanos** [comment]
V redu, sem dodal povezavo. Če boš še kaj spreminjala, mi javi, da jo posodobim.
