### ISSUE TITLE
knjižnica dplyr

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#2]
Ko želim zagnati moj 'uvoz' mi R vrne naslednje opozorilo: Warning in install.packages :
  package ‘dplry’ is not available (for R version 3.2.2)

Kako to odpravim, da mi bo uvoz deloval?

**Comment by jaanos** [comment]
Očitno si se zatipkala - knjižnici je ime `dplyr`, ne `dplry`.

**Comment by VezensekKaja** [comment]
Sedaj pa mi vrne to napako:
Error in library(dplyr) : there is no package called ‘dplyr’

**Comment by jaanos** [comment]
Si namestila dplyr? Če si, pa vseeno ne deluje, poskusi ugasniti in znova zagnati RStudio.

**Comment by VezensekKaja** [comment]
še vedno javlja napako.
Se lahko jutri oglasim pri vas za pomoč?

**Comment by jaanos** [comment]
Lahko - pridi ob 14h v kabinet 5.14.

**Comment by VezensekKaja** [comment]
Dogovorjeno, hvala.
