### ISSUE TITLE
skala grafa

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#3]
Ko želim grafu spremeniti skalo mi vrnje naslednjo napako:
Error: Discrete value supplied to continuous scale
Uporabila sem naslednjo funkcijo:
scale_y_continuous(limits = c(0,2000)) ki če prav razumem naredi skalo, ki gre od 0 do 2000 po korakih?

**Comment by jaanos** [comment]
Razlog, da naredi takšno lestvico na osi x je ta, da ti je števila iz CSV uvozilo kot nize. Ker v CSV uporabljaš decimalno piko, bo najlažje, če pri uvozu namesto `read.csv2` uporabiš `read.csv` (parameter `sep` imaš že nastavljen, tako da glede tega ne bo treba skrbeti). Potem ti bo tudi lestvico pravilno izrisalo.

**Comment by VezensekKaja** [comment]
ko sem spremenila read.csv2 v read.csv mi grafa sploh ne izriše ampak mi prikaže le prazno okno

**Comment by VezensekKaja** [comment]
sem poskusila še enkrat in sedaj deluje, hvala
