### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#4]
R mi noče odpreti PDF-ja čeprav mi napiše da naredi output file?

**Comment by VezensekKaja** [comment]
output file: projekt.knit.md

! I can't find file `t3enc.def'.
l.852 \input t3enc.def

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: There were 13 warnings (use warnings() to see them)
Execution halted

na koncu javi to

**Comment by jaanos** [comment]
Je potem to rešeno?

**Comment by VezensekKaja** [comment]
ja, sem zagnala še enkrat in je delovalo

**Comment by VezensekKaja** [comment]
ko sem dodala mesta v graf in želela ponovno PDF pa mi ga spet ne odpre..javi mi napako: error in parse

**Comment by VezensekKaja** [comment]
Po pomoti sem zbrisala nekaj in sem sedaj to popravila in spet dela
