### ISSUE TITLE
Branje HTML

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#5]
Dodala sem nov html in ko hočem da mi tabelo prikaže mi vrne R napako ''Error: could not find function "%>%" '', kako naj to popravim?

**Comment by jaanos** [comment]
`%>%` je del knjižnice dplyr, ki jo bo treba (skupaj z ostalimi) prej naložiti. Če torej poganjaš `uvoz.r` posebej, najprej poženi vrstico iz poročila, kjer uvoziš `libraries.r` (postavi se na vrstico ter pritisni Ctrl+Enter, ali klikni na _Run_).

Trenutno ti uvoz sicer ne deluje - očitno se je stran na Wikipediji spremenila. Da dobiš pravo tabelo, bo najbolje uvoz popraviti takole:

``` R
tabela <- stran %>% html_nodes(xpath="//table[@class='wikitable sortable']") %>% .[[1]] %>% html_table()
```

Sedaj torej iščeš tabelo, ki ima za atribut `class` vrednost `wikitable sortable`, kar pa je ravno iskana tabela.

**Comment by VezensekKaja** [comment]
Super, sedaj to deluje. Imam pa problem pri pretvorbi tabele v kodiranje UTF-8. napisala sem naslednje:
Encoding(tabela) <- "UTF-8"
in R mi vrne to napako:
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

Kaj moram spremeniti, da mi bo pretvorilo celotno tabelo v UTF-8? Hvala

**Comment by jaanos** [comment]
`Encoding` lahko nastaviš le za znakovne vektorje, torej posamezne stolpce z nizi. Najlažje bo, če to narediš za vsakega posebej:

``` R
Encoding(tabela[[1]]) <- "UTF-8"
Encoding(tabela[[7]]) <- "UTF-8"
Encoding(tabela[[8]]) <- "UTF-8"
Encoding(tabela[[9]]) <- "UTF-8"
```

Mimogrede, da bo R pravilno razumel številke, pri `html_table` dodaj parameter `dec = ","`. Tako bo pri površini pravilno razumljena decimalna vejica. Število prebivalcev, število naselij in leto bo potrebno še pretvoriti v števila - pred tem bo potrebno pobrisati pike (ločila tisočic), minuse (manjkajoče podatke) oziroma zvezdico (opomba).
