### ISSUE TITLE
Nova tabela

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#6]
Dodala sem novo tabelo, kjer sta zdruzeni csv tabela in pa html tabela. Poimenovala sem jo zdruzeno1.
Zanima me zakaj mi ob združitvi tabela zdruzeno1 ne vrne več vrednosti v pravilnem časovnem vrstnem redu (ne začne se več z letom 2007..) in če to vpliva na kasnejšo uporabo tabele?

**Comment by jaanos** [comment]
Vrstni red podatkov v tabeli ni pomemben - po potrebi lahko podatke vedno urediš z `arrange`.

Sicer pa svetujem, da namesto `merge` za združevanje uporabiš katero od funkcij `*_join` - iz dplyr, npr.

``` R
zdruzeno1 <- right_join(place, data.frame(tabela2)) %>%
  select(-starts_with('NA..')) %>% rename(`površina` = `NA.`)
```

Tukaj je funkcija `data.frame` potrebna, da preimenuje stolpce v `tabela2` tako, da imajo vsi različna imena (sicer `right_join` ne bo deloval). Seveda bi bilo smiselno, da že pred združevanjem preimenuješ stolpce razpredelnice `tabela2` in nepotrebne stolpce izpustiš. Potem seveda izpuščanje in preimenovanje po združitvi ne bo potrebno.

Da ti površino razume kot število, funkciji `html_table` dodaj parameter `dec = ","` (trenutno sicer vejice zamenjaš s pikami, a dobljenih nizov ne pretvoriš v števila).

Še to: nekatera imena občin se razlikujejo med razpredelnicama `place` in `tabela2`. `right_join` poskrbi, da se v združeni razpredelnici ohranijo vse vrstice iz druge razpredelnice (torej `tabela2`). Podobno ti `left_join` ohrani vse vrstice iz prve razpredelnice, `full_join` iz obeh, `inner_join` pa ohrani samo tiste vrstice, ki se pojavijo v obeh razpredelnicah. Če hočeš torej videti, katera imena iz `tabela2` se ne ujemajo s tistimi v `place` (in torej nimajo podatkov iz te razpredelnice), lahko poženeš npr.

``` R
zdruzeno1 %>% filter(is.na(leto))
```

Najbolje bo, če pred združevanjem ta imena nadomestiš z ustreznimi iz `place`, da bo združitev popolna.
