### ISSUE TITLE
Prikaz grafa s tidy data

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#7]
Sedaj, ko imam celotno tabelo v tidydata me zanima, kako na x osi uporabiti dva paramatra? Torej leto in mesec? Želim namreč, da bo graf spet gladek kot je bil prej

**Comment by jaanos** [comment]
ggplot2 podpira datumske osi, le podati mu je treba objekte tipa `Date`. Te lahko sestaviš iz stolpcev `leto` in `mesec`, npr.

``` R
meseci <- c("Januar" = 1, "Julij" = 7)
ggplot(filter(place,
              kraj %in% c("Koper/Capodistria", "Ljubljana", "Maribor", 'Celje', 'Murska Sobota', 'Nova Gorica', 'Kranj', 'Novo Mesto')) %>%
         mutate(datum = paste(leto, meseci[mesec], 1, sep = "-") %>% as.Date()),
       aes(x=datum, y=neto, group = kraj, color = kraj)) +
  geom_line() + theme(axis.text.x = element_text(angle=60, hjust=1))
```

Z `mutate` torej narediš nov stolpec `datum`, ki ga sestaviš tako, da zlepiš skupaj leto, številko meseca in enico (za prvi dan v msesecu - da imaš pač veljaven datum), potem pa dobljeni niz z `as.Date` pretvoriš v datum, ki ga bo ggplot2 razumel.
