### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#8]
Zanima me, zakaj mi kljub temu, da sem spremenila podatke za zamljevid le tega ne izriše.. (v mapi vizualizacija)

**Comment by jaanos** [comment]
Trenutno poskušaš risati zemljevid iz razpredelnice `zdr`, ki pa ne vsebuje zemljevida. Uvoženi zemljevid bo potrebno pretvoriti in ga združiti z izbranimi podatki iz razpredelnice, npr.

``` R
ob <- pretvori.zemljevid(placepoobcinah)
zem <- ggplot() + geom_polygon(data = zdr %>%
                                 filter(leto == 2007, mesec == "Januar") %>%
                                 right_join(ob, by = c("kraj" = "OB_UIME")),
                               aes(x=long, y=lat, group=group, fill=neto),
                               color = "grey") +
  scale_fill_gradient(low="#3F7F3F", high="#00FF00") +
  guides(fill = guide_colorbar(title = "neto"))
```

Opaziš lahko, da za nekatere občine podatki niso prikazani - tako kot pri #6 je krivo to, da se imena ne ujemajo popolnoma. Izkaže se, da v `OB_UIME` okoli pomišljajev ni presledkov, pa še tri imena se razlikujejo. Tako lahko to popraviš pred pretvorbo zemljevida:

``` R
placepoobcinah$kraj <- gsub("-", " - ", placepoobcinah$OB_UIME)
placepoobcinah$kraj[placepoobcinah$kraj == "Kanal"] <- "Kanal ob Soči"
placepoobcinah$kraj[placepoobcinah$kraj == "Loški Potok"] <- "Loški potok"
placepoobcinah$kraj[placepoobcinah$kraj == "Sveti Andraž v Slovenskih goricah"] <- "Sveti Andraž v Slov. goricah"
```

Sedaj bo zemljevid imel stolpec `kraj` (torej enako kot v `zdr`), tako da lahko parameter `by` pri `right_join` izpustiš (lahko bi pa pisala `by = c("kraj" = "kraj")`, ali pa samo `by = "kraj"`). Tudi opozorila več ne bo, saj sta sedaj oba stolpca `kraj` znakovna (`OB_UIME` je pa faktor).

**Comment by VezensekKaja** [comment]
Žal mi zemljevida še vedno ne prikaže pravilno. napiše mi namreč napako:
Warning message:
In right_join_impl(x, y, by$x, by$y) :
  joining character vector and factor, coercing into character vector

**Comment by jaanos** [comment]
To je samo opozorilo, zemljevid se bo še vedno izrisal, če poženeš `print(zem)`. Da odpraviš opozorilo, reši problem z neujemajočimi imeni, kot je opisano v zgornjem komentarju.

**Comment by VezensekKaja** [comment]
Sem dodala tudi kar ste napisali zgoraj za neujemajoča imena, vendar mi še vedno javi isto napako in pa nekatere občine obarva sivo

**Comment by jaanos** [comment]
Ali lahko naložiš trenutno verzijo, da vidim, kaj gre narobe?

**Comment by VezensekKaja** [comment]
sem sedajle dodala

**Comment by jaanos** [comment]
Vrstico `ob <- pretvori.zemljevid(placepoobcinah)` premakni za spremembe imen občin, pri `right_join` pa odstrani parameter `by`.

Še to: očitno sem za Sveti Andraž v Slovenskih goricah zamenjal imeni, tako da bo pravilno takole:

``` R
placepoobcinah$kraj[placepoobcinah$kraj == "Sveti Andraž v Slov. goricah"] <- "Sveti Andraž v Slovenskih goricah"
```

Da bo zemljevid izrisovalo hitreje, lahko takoj za tem (torej preden kličeš `pretvori.zemljevid`) še oba stolpca `kraj` pretvoriš v faktorja:

``` R
placepoobcinah$kraj <- factor(placepoobcinah$kraj)
zdr$kraj <- factor(zdr$kraj)
```

**Comment by VezensekKaja** [comment]
sem spremenila in dodala, ampak sta dve občini (piran in še ena) še vedno obarvani sivo

**Comment by jaanos** [comment]
Tisto sta Ankaran in Mirna, ki leta 2007 še nista obstajali.

**Comment by VezensekKaja** [comment]
vredu, hvala

**Comment by VezensekKaja** [comment]
Zanima me še kako določiti, da naj pike za mesta in njihova imena izpiše le za vsa mesta, ki imajo neto plačo nad 1200? Pri vajah smo namreč gledali samo že direktno znane podatke iz tabele, torej ali je bila občina mestna ali ne.

**Comment by jaanos** [comment]
Podatke lahko filtriraš s `filter`. Da narišeš ustrezne pike, lahko tako obstoječemu zemljevidu prišteješ npr.

``` R
geom_point(data = zdr %>%
               filter(leto == 2007, mesec == "Januar", bruto > 1200) %>%
               inner_join(placepoobcinah@data), aes(x = Y_C, y = X_C))
```

Seveda si lahko te (delno) filtrirane/združene razpredelnice pripraviš že vnaprej, da se stvari ne bodo ponavljale.

**Comment by VezensekKaja** [comment]
To sedaj deluje, zanima me samo še kater 'label' dodati, da bo izpisalo imena občin..

**Comment by jaanos** [comment]
Za `label` daš ime stolpca z imeni krajev, torej `kraj`. Ker je to spremenljivka, ga podaj znotraj `aes`.

**Comment by VezensekKaja** [comment]
če samo zaženem zemljevid mi to deluje, če pa ga hočem izpisati v poročilu pa javi to napako:
Quitting from lines 57-58 (projekt.Rmd) 
Error: Aesthetics must be either length 1 or the same as the data (21): label, size, vjust
In addition: There were 12 warnings (use warnings() to see them)
Execution halted

**Comment by jaanos** [comment]
`zem3` riši tako:

``` R
zem3 <- zem2 + geom_text(data = zdr %>% filter(leto == 2015, mesec == "Julij", neto > 1000)
                         %>% inner_join(placepoobcinah@data),
                         aes(x = Y_C, y = X_C, label = kraj),
                         size = 3, vjust = 2)
```

**Comment by VezensekKaja** [comment]
še vedno mi javi isto napako

**Comment by VezensekKaja** [comment]
sem kopiralo celotno kodo iz vizualizacije v poročilo in sedaj deluje..

**Comment by jaanos** [comment]
V redu, zdaj prevede, tako da bom dodal povezavo.

Dve pripombi:
- V RMarkdownu `#` ne pomeni komentarja, pač pa naslov. Zato umakni lojtre pred vrsticama, ki označujeta začetek in konec bloka kode (sama vrstica kode je seveda lahko zakomentirana. Lahko pa celoten blok odstraniš.
- Bloku kode, kjer rišeš zemljevid, dodaj še parameter `message = FALSE`, da se v poročilo ne bodo izpisovala sporočila.
