### ISSUE TITLE
Nov stolpec

### ISSUE THREAD

**Issue by VezensekKaja** [VezensekKaja/APPR-2015-16#9]
Pozdravljeni,
V tabelo sem želela dodati nov stolpec, ki bi bil izračunan iz prejšnjih vrstic, ampak mi naj nebi prepoznalo stolpca 'bruto'. Ker sem že malo pozabila kako se R uporablja je verjetno koda napačna, za kar se opravičujem in vas zalo lepo prosim za pomoč pri izdelavi stolpca. Potem pa bom sama nadaljevala v Shineju.

**Comment by jaanos** [comment]
Morda bo najlažje, če za dodajanje novih stolpcev uporabiš `mutate`:

``` R
zdr <- mutate(zdr, `Bruto/površina` = bruto/površina)
```

Tvoj način bi sicer deloval, če bi imeni stolpcev `bruto` in `površina` podala kot niza.

**Comment by VezensekKaja** [comment]
Ko sem dodala stolpec sem iz njega naredila še graf in graf mi nariše, če ga zaženem v uvozu, ko pa ga dam v poročilo mi ga ne prevede, saj reče, da je napaka že v uvozu (čeprav mi sam uvoz dela normalno)..

**Comment by VezensekKaja** [comment]
sem poskusila še enkrat in je delovalo
